"""empty message

Revision ID: b7956dd8cfcd
Revises: 6301c3aa96ae
Create Date: 2020-02-22 14:29:37.132000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7956dd8cfcd'
down_revision = '6301c3aa96ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('uri', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'uri')
    # ### end Alembic commands ###
