"""empty message

Revision ID: fdc2c0497c4d
Revises: b7956dd8cfcd
Create Date: 2020-02-23 19:10:53.355000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc2c0497c4d'
down_revision = 'b7956dd8cfcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catstags', sa.Column('catag_colour', sa.Text(), nullable=True))
    op.alter_column('posts', 'uri',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'posts', ['uri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.alter_column('posts', 'uri',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('catstags', 'catag_colour')
    # ### end Alembic commands ###
